### ISSUE TITLE
Videographer may apply a filter to multiple movies at the same time

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/mp-movielooks#1]
In order to save time when working with multiple clips
As a videographer
I would like to be able to apply the MovieLooks filter to a number of clips at the same time

## This Issue May Be Closed When

- [ ] There is an appropriately defined set of scenarios exercising this enhancement stored in the `features/applying-filters.feature` 
  - [ ] "Happy Path" 
  - [ ] One or more "Sad Paths" 
- [ ] There are a set of low-or-high fidelity mockups that indicate the intended flow for this use case
- [ ] A non-programmer can verify the multiple movie conversion functions as intended on the TestFlight build
- [ ] The feature has been announced to the members of the Moment Park mailing list.
- [ ] The customer(s) who have requested this feature have been emailed with a notification that it is in production.
  - [ ] D. S. (https://groups.google.com/a/zincma.de/forum/#!topic/hello/aIgCaMANfBY)
