### ISSUE TITLE
Videographer may apply the MovieLooks filter when working within other iOS Apps

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/mp-movielooks#2]
In order to save time when working with larger projects
As a videographer
I would like to be able to apply the Movie Looks filter while working within other iOS applications

### This Issue May Be Closed When

- [ ] There is an appropriately defined set of scenarios exercising this enhancement stored in the `features/applying-filters.feature`
  - [ ]  Happy Path
  - [ ] Sad Path(s)
- [ ] There are a set of low-or-high-fidelity mockups that indicate the intended flow for this use case.
- [ ] A non-programmer can verify that they can send clips  to MovieLooks when working within other iOS applications on the TestFlight build
- [ ] The feature has been announced to the members of the Moment Park mailing list
- [ ] The customer(s) who have requested this feature have been emailed with a notification that it is in production.
  - [ ] [D. S.](https://groups.google.com/a/zincma.de/forum/#!topic/hello/aIgCaMANfBY)
