### ISSUE TITLE
Videographer may apply a "mask"  to adjust the effect on part of the image

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/mp-movielooks#3]
In order to have more creative control over the resulting filter
As a Videographer
I would like to use simple shaped masks on sections of the view-window

### This Issue May Be Closed When

- [ ] There is an appropriately defined set of scenarios illustrating the usage of masks, stored in `features/masking-filters.feature
  - [ ] Happy Paths:
    - [ ] Rectangle
    - [ ] Circle
    - [ ] Gradated/Featured
    - [ ] Invert
- [ ] There are a set of low-or-high fidelity mockups that indicate the indended flow for this use case
- [ ] A non-programmer can verify the usage of these masks in the TestFlight build
- [ ] The feature has been announced to the members of the Moment Park mailing list
- [ ] The customer(s) who have requested this feature have been emailed with a notification that it is in production.
  - [ ] [D.S.](https://groups.google.com/a/zincma.de/forum/#!topic/hello/aIgCaMANfBY)
